export const keyValue = {
  //Weekly Subcategory table
  key1: '항목',
  ke2: '재고',
  key3: '매출비중',
  key4: '전년비',
  key5: '재고주수',
  key6: '판매율',
  key7: '판매량',
  key8: '날짜',
  key9: '위탁총판매',
  key10: '국내',
  key11: '면세RF도매',
  key12: '중국',
  key13: '홍마대',
  key14: '항목',
  key15: '제품명',
  key16: '제품코드',
  key17: '항목',
  key18: '비중',
  key19: '판매량 (당해)',
  key20: '판매량 (전년)',
  key21: '전년비',
  key22: '제품이미지',
};
